import { PrismaClient, MissionPriority, MissionStatus } from '@prisma/client'
const prisma = new PrismaClient()

// Helper: convert array → JSON string for SQLite
function arr(s: string[]): string { return JSON.stringify(s) }

const missions = [
  {
    title: 'Crop Yield Prediction for Smallholder Farmers in Sub-Saharan Africa',
    slug: 'crop-yield-prediction-africa',
    description: 'Build a model that predicts crop yields using satellite imagery, weather data, and soil composition to help smallholder farmers optimize planting and reduce food insecurity.',
    domain: 'agriculture', priority: MissionPriority.CRITICAL, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 2: Zero Hunger', 'SDG 13: Climate Action'],
    requiredCapabilities: ['satellite-analysis', 'data-analysis', 'edge-ml'],
    successCondition: 'Model achieves ≥85% accuracy on held-out test set across 5+ countries',
    taskDecomposition: { type: 'object', value: [
      { title: 'Data collection: satellite imagery from Sentinel-2', description: 'Collect and preprocess multi-temporal satellite data' },
      { title: 'Data collection: weather and soil databases', description: 'Integrate ERA5 weather and SoilGrids soil data' },
      { title: 'Model training: baseline LSTM on time-series', description: 'Implement temporal crop yield prediction model' },
      { title: 'Edge deployment: quantize model for mobile inference', description: 'Convert model to ONNX/TFLite for low-resource devices' },
      { title: 'Validation: field testing in pilot regions', description: 'Validate predictions against ground truth harvest data' },
    ]},
  },
  { title: 'Malaria Transmission Hotspot Mapping', slug: 'malaria-hotspot-mapping',
    description: 'Develop a real-time malaria transmission risk mapping system using environmental sensors, case reports, and climate data.',
    domain: 'health', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'WHO', sdgAlignment: ['SDG 3: Good Health', 'SDG 6: Clean Water'],
    requiredCapabilities: ['geospatial', 'nlp', 'data-analysis'],
    successCondition: 'Map achieves ≥90% precision in predicting hotspot clusters validated against field data',
  },
  { title: 'Wildfire Early Warning System for California', slug: 'wildfire-early-warning',
    description: 'Create a wildfire early warning system combining satellite thermal data, atmospheric conditions, and vegetation dryness indices.',
    domain: 'climate', priority: MissionPriority.CRITICAL, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 11: Sustainable Cities', 'SDG 13: Climate Action'],
    requiredCapabilities: ['satellite-analysis', 'edge-ml', 'data-analysis'],
    successCondition: 'Early warning provides ≥72 hours advance notice with <10% false positive rate',
  },
  { title: 'Ocean Plastic Pollution Tracking and Source Attribution', slug: 'ocean-plastic-tracking',
    description: 'Develop an ocean plastic pollution monitoring system using satellite and drone imagery to track accumulation zones.',
    domain: 'environment', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 14: Life Below Water', 'SDG 12: Responsible Consumption'],
    requiredCapabilities: ['satellite-analysis', 'computer-vision', 'geospatial'],
    successCondition: 'System accurately maps 95% of known microplastic accumulation zones within ±5km',
  },
  { title: 'Deforestation Detection in the Amazon Basin', slug: 'amazon-deforestation-detection',
    description: 'Build a near-real-time deforestation detection system for the Amazon using SAR satellite data that works through cloud cover.',
    domain: 'environment', priority: MissionPriority.CRITICAL, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 15: Life on Land', 'SDG 13: Climate Action'],
    requiredCapabilities: ['satellite-analysis', 'nlp', 'low-resource-ml'],
    successCondition: 'Detects deforestation events within 48 hours with ≥97% accuracy',
  },
  { title: 'Water Quality Monitoring for Developing Regions', slug: 'water-quality-monitoring',
    description: 'Design a low-cost sensor network and ML model that monitors water quality parameters in real-time across water-scarce regions.',
    domain: 'health', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'WHO', sdgAlignment: ['SDG 6: Clean Water', 'SDG 3: Good Health'],
    requiredCapabilities: ['edge-ml', 'data-analysis', 'multilingual'],
    successCondition: 'Sensor + model achieves ≥95% correlation with lab testing across 20+ water types',
  },
  { title: 'Pandemic Forecasting: Respiratory Disease Outbreaks', slug: 'pandemic-forecasting-respiratory',
    description: 'Develop an early warning system for respiratory disease outbreaks using search trends, hospital data, and climate patterns.',
    domain: 'health', priority: MissionPriority.CRITICAL, status: MissionStatus.OPEN,
    sourceFramework: 'WHO', sdgAlignment: ['SDG 3: Good Health', 'SDG 17: Partnerships'],
    requiredCapabilities: ['nlp', 'data-analysis', 'epidemiology'],
    successCondition: 'Forecast achieves ≥80% accuracy for outbreaks ≥2 weeks in advance',
  },
  { title: 'Coral Reef Health Assessment from Satellite Imagery', slug: 'coral-reef-health',
    description: 'Automate coral reef health assessment by combining sea surface temperature, spectral imagery, and in-situ bleaching reports.',
    domain: 'environment', priority: MissionPriority.MEDIUM, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 14: Life Below Water', 'SDG 13: Climate Action'],
    requiredCapabilities: ['satellite-analysis', 'computer-vision', 'data-analysis'],
    successCondition: 'Automated assessment achieves ≥90% agreement with expert diver surveys',
  },
  { title: 'Air Quality Prediction for South Asian Megacities', slug: 'air-quality-south-asia',
    description: 'Build an air quality prediction system for Delhi, Dhaka, Kathmandu, and Karachi using IoT, satellite AOD, and traffic data.',
    domain: 'health', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 3: Good Health', 'SDG 11: Sustainable Cities'],
    requiredCapabilities: ['data-analysis', 'nlp', 'multilingual'],
    successCondition: 'AQI predictions achieve ≥90% accuracy for next 7 days across all 4 cities',
  },
  { title: 'Groundwater Depletion Mapping via GRACE Satellite Data', slug: 'groundwater-depletion-mapping',
    description: 'Analyze GRACE gravimetry data combined with surface water observations for a groundwater depletion map of South and Southeast Asia.',
    domain: 'environment', priority: MissionPriority.MEDIUM, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 6: Clean Water', 'SDG 15: Life on Land'],
    requiredCapabilities: ['data-analysis', 'satellite-analysis', 'geospatial'],
    successCondition: 'Map achieves ≤5% error against well depth measurements from 1000+ monitoring wells',
  },
  { title: 'Drought Early Warning for the Horn of Africa', slug: 'drought-early-warning-horn-africa',
    description: 'Develop a drought prediction system for Ethiopia, Somalia, and Kenya using vegetation indices, rainfall data, and livestock indicators.',
    domain: 'agriculture', priority: MissionPriority.CRITICAL, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 2: Zero Hunger', 'SDG 13: Climate Action'],
    requiredCapabilities: ['satellite-analysis', 'data-analysis', 'edge-ml'],
    successCondition: 'Drought conditions predicted ≥4 months in advance with ≥85% accuracy',
  },
  { title: 'School Enrollment Gap Analysis in Sub-Saharan Africa', slug: 'school-enrollment-gap-africa',
    description: 'Analyze satellite nighttime lights, population density, and ground surveys to identify school access gaps in rural sub-Saharan Africa.',
    domain: 'social', priority: MissionPriority.MEDIUM, status: MissionStatus.OPEN,
    sourceFramework: 'UNICEF', sdgAlignment: ['SDG 4: Quality Education', 'SDG 10: Reduced Inequalities'],
    requiredCapabilities: ['geospatial', 'data-analysis', 'computer-vision'],
    successCondition: 'Gap analysis identifies school-desert areas with ≥92% agreement against ground truth',
  },
  { title: 'Ebola Outbreak Surveillance System', slug: 'ebola-surveillance-system',
    description: 'Build a real-time Ebola surveillance system combining case reports, mobility data, forest cover changes, and wildlife migration.',
    domain: 'health', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'WHO', sdgAlignment: ['SDG 3: Good Health', 'SDG 15: Life on Land'],
    requiredCapabilities: ['nlp', 'epidemiology', 'geospatial'],
    successCondition: 'System detects early outbreak signals ≥30 days before WHO declaration',
  },
  { title: 'Urban Heat Island Mitigation Planning', slug: 'urban-heat-island',
    description: 'Use thermal satellite imagery and urban morphology to identify hottest neighborhoods and recommend cooling interventions.',
    domain: 'climate', priority: MissionPriority.MEDIUM, status: MissionStatus.OPEN,
    sourceFramework: 'IPCC', sdgAlignment: ['SDG 11: Sustainable Cities', 'SDG 13: Climate Action'],
    requiredCapabilities: ['satellite-analysis', 'data-analysis', 'geospatial'],
    successCondition: 'Intervention plan reduces predicted peak temperatures by ≥3°C in target zones',
  },
  { title: 'Soil Carbon Sequestration Monitoring', slug: 'soil-carbon-monitoring',
    description: 'Develop a methodology for quantifying soil carbon sequestration rates from satellite data for carbon credit verification.',
    domain: 'climate', priority: MissionPriority.MEDIUM, status: MissionStatus.OPEN,
    sourceFramework: 'IPCC', sdgAlignment: ['SDG 13: Climate Action', 'SDG 15: Life on Land'],
    requiredCapabilities: ['data-analysis', 'satellite-analysis', 'low-resource-ml'],
    successCondition: 'Satellite-derived carbon estimates achieve ±15% agreement with ground sample measurements',
  },
  { title: 'Maternal Health Access Mapping', slug: 'maternal-health-access',
    description: 'Map maternal healthcare access across South Asia using GPS hospital locations, road networks, and cultural barriers.',
    domain: 'health', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'UNICEF', sdgAlignment: ['SDG 3: Good Health', 'SDG 5: Gender Equality'],
    requiredCapabilities: ['geospatial', 'nlp', 'multilingual'],
    successCondition: 'Map identifies 95% of maternal mortality hotspots with ≤10% false positive rate',
  },
  { title: 'Fish Stock Assessment for the South China Sea', slug: 'fish-stock-assessment',
    description: 'Estimate fish stock levels using satellite-derived sea surface temperature, chlorophyll concentration, and fishing vessel AIS data.',
    domain: 'environment', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 14: Life Below Water', 'SDG 2: Zero Hunger'],
    requiredCapabilities: ['satellite-analysis', 'data-analysis', 'nlp'],
    successCondition: 'Stock estimates achieve ≥85% accuracy against commercial fishing catch data',
  },
  { title: 'Indigenous Language Preservation through AI', slug: 'indigenous-language-preservation',
    description: 'Build a multilingual NLP toolkit for 20 critically endangered languages to document and preserve indigenous knowledge.',
    domain: 'social', priority: MissionPriority.MEDIUM, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 4: Quality Education', 'SDG 10: Reduced Inequalities'],
    requiredCapabilities: ['nlp', 'multilingual', 'low-resource-ml'],
    successCondition: 'NLP toolkit achieves ≥70% performance on held-out test sets for all 20 languages',
  },
  { title: 'Renewable Energy Microgrid Optimization', slug: 'renewable-microgrid-optimization',
    description: 'Develop an optimization algorithm for solar + battery microgrids in off-grid African villages.',
    domain: 'energy', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 7: Affordable Energy', 'SDG 13: Climate Action'],
    requiredCapabilities: ['data-analysis', 'edge-ml'],
    successCondition: 'Optimized microgrid achieves ≥99% uptime at ≤80% cost of baseline configurations',
  },
  { title: 'Landmine Detection Using Ground Penetrating Radar ML', slug: 'landmine-detection',
    description: 'Train a machine learning model to interpret ground penetrating radar data for automated landmine detection.',
    domain: 'social', priority: MissionPriority.HIGH, status: MissionStatus.OPEN,
    sourceFramework: 'UN SDG', sdgAlignment: ['SDG 11: Sustainable Cities', 'SDG 16: Peace and Justice'],
    requiredCapabilities: ['edge-ml', 'data-analysis', 'computer-vision'],
    successCondition: 'Model achieves ≥99% detection accuracy with ≤1% false positive rate in blind testing',
  },
]

async function main() {
  console.log('🌱 Seeding Pragma...\n')
  const curator = await prisma.user.upsert({
    where: { email: 'curator@pragma.global' },
    update: {},
    create: { email: 'curator@pragma.global', name: 'Pragma Curator', role: 'CURATOR' },
  })

  for (const m of missions) {
    const mission = await prisma.mission.upsert({
      where: { slug: m.slug },
      update: {
        ...m,
        sdgAlignment: arr(m.sdgAlignment),
        requiredCapabilities: arr(m.requiredCapabilities),
      },
      create: { ...m, sdgAlignment: arr(m.sdgAlignment), requiredCapabilities: arr(m.requiredCapabilities), curatorUserId: curator.id },
    })
    console.log('  ✅', m.slug)

    // Create tasks from taskDecomposition if present
    const td = m.taskDecomposition as { type: string; value: { title: string; description: string }[] } | undefined
    if (td && Array.isArray(td.value)) {
      for (const t of td.value) {
        await prisma.task.upsert({
          where: { id: `${mission.slug}-${t.title.slice(0, 30).replace(/[^a-z0-9]/g, '-')}` },
          update: {},
          create: {
            id: `${mission.slug}-${t.title.slice(0, 30).replace(/[^a-z0-9]/g, '-')}`,
            missionId: mission.id,
            title: t.title,
            description: t.description,
            requiredCapabilities: arr(m.requiredCapabilities),
            status: 'OPEN',
          },
        })
      }
    }
  }

  const count = await prisma.mission.count()
  console.log(`\n🎉 Done! ${count} missions in database.`)
}

main().catch(e => { console.error('Seed failed:', e); process.exit(1) })
